[libraries]
groovy-all = { group = "org.codehaus.groovy", name = "groovy-all", version = "3.0.25" }
codenarc = { group = "org.codenarc", name = "CodeNarc", version = "3.7.0" }
spock-core = { group = "org.spockframework", name = "spock-core", version = "2.4-groovy-3.0" }
